name: Terraform Deploy to AWS

on:
  # push:
  #   branches:
  #     - main   # or your preferred branch
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  terraform:
    name: Terraform Init & Apply
    runs-on: ubuntu-latest
    environment:
      name: production   # Triggers manual approval via GitHub UI

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }} #1.7.5  # Choose your desired version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Wait for manual approval
        run: echo "Waiting for manual approval in GitHub UI..."

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
